title: Cecelia Soh
description: >
  📧 <a href="mailto:ceceliasoh1030@gmail.com">ceceliasoh1030@gmail.com</a><br>
  <a href="https://www.linkedin.com/in/cecelia-soh-6b3522217/" target="_blank">
    <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/linkedin.svg" alt="LinkedIn" width="16" style="vertical-align:middle; margin-right:4px;">
    LinkedIn
  </a>
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
