title: Cecelia Soh
theme: jekyll-theme-minimal
description: >
  📧: ceceliasoh1030@gmail.com
  <a href="https://www.linkedin.com/in/cecelia-soh-6b3522217/" target="_blank">
    <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/linkedin.svg" alt="LinkedIn" width="16" style="vertical-align:middle; margin-right:4px;">
    LinkedIn
  </a>
